# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.overridePathCheck=true

# AndroidX support
android.useAndroidX=true
android.enableJetifier=true

# Quan tr?ng: Ng?n Gradle dùng JRE c?a Cursor (thi?u jlink)
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=true
